In [1]:
import torch
from torch import empty , cat , arange
from torch.nn.functional import fold , unfold

kernel = empty((5,5)).normal_()
print(kernel.view(1,-1))
print(kernel)
print(kernel.flip((0,1)))

tensor([[-1.4051, -1.7177, -0.7964,  1.6586,  0.3451,  1.2268, -0.7717, -1.3647,
         -1.2632,  0.4795,  1.0399,  1.0148, -0.8453, -0.0493, -0.0384,  0.0330,
         -0.4317,  1.1544,  0.1728,  1.1966, -1.0152, -1.2436,  1.4244,  0.3388,
         -0.2548]])
tensor([[-1.4051, -1.7177, -0.7964,  1.6586,  0.3451],
        [ 1.2268, -0.7717, -1.3647, -1.2632,  0.4795],
        [ 1.0399,  1.0148, -0.8453, -0.0493, -0.0384],
        [ 0.0330, -0.4317,  1.1544,  0.1728,  1.1966],
        [-1.0152, -1.2436,  1.4244,  0.3388, -0.2548]])
tensor([[-0.2548,  0.3388,  1.4244, -1.2436, -1.0152],
        [ 1.1966,  0.1728,  1.1544, -0.4317,  0.0330],
        [-0.0384, -0.0493, -0.8453,  1.0148,  1.0399],
        [ 0.4795, -1.2632, -1.3647, -0.7717,  1.2268],
        [ 0.3451,  1.6586, -0.7964, -1.7177, -1.4051]])


In [2]:
kernel = empty((3,3)).normal_()
print(kernel)
print(kernel.flip(0,1))

tensor([[ 0.8814,  0.1914,  0.3235],
        [ 0.4294,  0.3043, -1.0695],
        [-0.5244,  0.2586,  0.4543]])
tensor([[ 0.4543,  0.2586, -0.5244],
        [-1.0695,  0.3043,  0.4294],
        [ 0.3235,  0.1914,  0.8814]])


In [146]:
im_size = 2

k_size = 3
padding_input = 0
p_size = k_size -1

image = torch.empty((1,1,im_size,im_size)).normal_()
kernel = torch.empty((1,1,k_size,k_size)).normal_()

image = torch.ones((1,1,im_size,im_size))
kernel = torch.ones((1,1,k_size,k_size))
padded_kernel = torch.nn.functional.pad(kernel, (padding_input, padding_input, padding_input, padding_input))

test = torch.nn.functional.conv_transpose2d(image, kernel, stride=3, padding = 0)
test2 = torch.nn.functional.conv_transpose2d(image, padded_kernel, stride=1, padding = 0)

print(test.shape)
print(test)

torch.Size([1, 1, 6, 6])
tensor([[[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]]])


In [95]:
unfolded = unfold(image, kernel_size = k_size, stride = 1, padding=p_size)
out = kernel.view(1, -1) @ unfolded
result = out.view(1, 1, im_size+p_size, im_size+p_size)
print(result)

tensor([[[[1., 2., 2., 1.],
          [2., 4., 4., 2.],
          [2., 4., 4., 2.],
          [1., 2., 2., 1.]]]])


In [93]:
folded = fold(unfolded, (im_size,im_size), k_size)
print(folded)

tensor([[[[1., 2., 1.],
          [2., 4., 2.],
          [1., 2., 1.]]]])


In [82]:
out.transpose(1,2)

tensor([[[1.],
         [2.],
         [2.],
         [1.],
         [2.],
         [4.],
         [4.],
         [2.],
         [2.],
         [4.],
         [4.],
         [2.],
         [1.],
         [2.],
         [2.],
         [1.]]])